bookShopProject/Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bookShopProject.Models;
namespace bookShopProject.Controllers
{
    public class userController : Controller
    {
        private bookShopEntities _db = new bookShopEntities();
        // GET: user
        public ActionResult Index()
        {
            if (Session["userId"] == null)
            {
                Response.Redirect("~/user/Login");
            }
            return View(_db.User.ToList());
        }

        // GET: user/Details/5
        public ActionResult Details(int id)
        {
            var userInfo = _db.User.Where(x => x.userDetails_id == id).FirstOrDefault();
            var userDetails = _db.userDetails.Find(userInfo.userDetails_id);
            ViewBag.id= userInfo.id;
            return View(userDetails);
        }

        // GET: user/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: user/Create
        [HttpPost]
        public ActionResult Create(ViewModel.userViewModel obj)
        {
            var userInfo = _db.User.Where(x => x.username == obj.username).FirstOrDefault();
            if (userInfo != null)
            {
                ViewBag.usernameErrorMessage = "Taki użytkownik już Istnieje,Wprowadź inny login";
                return View("Create", obj);
            }
            else
            { 
             userDetails ud = new userDetails();
            ud.name = obj.name;
            ud.surname = obj.surname;
            ud.postCode = obj.postCode;
            ud.street = obj.street;
            ud.houseNumber = obj.houseNumber;
            ud.phoneNumber = obj.phoneNumber;
            _db.userDetails.Add(ud);
            _db.SaveChanges();
            User u = new User();
            u.username = obj.username;
            u.password = obj.password;
            u.Role = obj.Role;
            u.userDetails_id = ud.id;
            _db.User.Add(u);
            _db.SaveChanges();

            return RedirectToAction("Index");
            }
           
        } 

        // GET: user/Edit/5
        public ActionResult Edit(int id)
        {
            var userToEdit = _db.User.SingleOrDefault(m => m.id == id); ;
            return View(userToEdit);
        }

        // POST: user/Edit/5
        [HttpPost]
        public ActionResult Edit(User userToEdit)
        {
            var originalUser = _db.User.SingleOrDefault(m => m.id == userToEdit.id);
            try
            {
                // TODO: Add update logic here
                if (TryUpdateModel(originalUser, new string[] {
                    "username", "password", "Role","userDetails_id" }))
                {
                    _db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View(originalUser);
            }
        }

        // GET: user/Delete/5
        public ActionResult Delete(int id)
        {
            var userToDelete = _db.User.SingleOrDefault(m => m.id == id);
            return View(userToDelete);
        }

        // POST: user/Delete/5
        [HttpPost]
        public ActionResult Delete(User userToDelete)
        {
                var deleteUser = _db.User.SingleOrDefault(m => m.id == userToDelete.id);
                var deleteUserDetails = _db.userDetails.SingleOrDefault(m => m.id == deleteUser.userDetails_id);
                _db.Order.RemoveRange(_db.Order.Where(c => c.User_id == deleteUser.id));
                _db.SaveChanges();
                _db.cart.RemoveRange(_db.cart.Where(c => c.User_id == deleteUser.id));
                _db.SaveChanges();
                _db.User.Remove(deleteUser);
                _db.SaveChanges();
                _db.userDetails.Remove(deleteUserDetails);
                _db.SaveChanges();

                return RedirectToAction("Index");
         
        }
        public ActionResult LogIn()
        {
            return View();
        }
        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("Index","Home");
        }
        [HttpPost]
        public ActionResult Authorize(User userModel)
        {
            using (_db)
            {
                var userInfo = _db.User.Where(x => x.username == userModel.username && x.password == userModel.password).FirstOrDefault();
                if (userInfo == null)
                {
                    userModel.LoginErrorMessage = "Nieprawidłowy login lub hasło!";
                    return View("LogIn", userModel);
                }
                else
                {
                    Session["userId"] = userInfo.id;
                    Session["role"] = userInfo.Role;
                    Session["name"] = userInfo.userDetails.name+" "+ userInfo.userDetails.surname;
                    return RedirectToAction("Index", "Home");
                }
              
            }
        }
    }
}

bookShopProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>

        $.validator.methods.range = function (value, element, param) {
            var globalizedValue = value.replace(",", ".");
            return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
        }

        $.validator.methods.number = function (value, element) {
            return this.optional(element) || /-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }
        //Date dd/MM/yyyy
        $.validator.methods.date = function (value, element) {
            var date = value.split("/");
            return this.optional(element) || !/Invalid|NaN/.test(new Date(date[2], date[1], date[0]).toString());
        }
    </script>
    <link href="~/Content/footerCss.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img src="~/logoFolder/logo.svg" />
                </a>
                

            </div>
            <div class="navbar-left" style="margin-top:12px;">
                @using (Html.BeginForm("searchForBook", "book", FormMethod.Post))
                {
                    <ul class="nav navbar-nav">
                        <li><input type="text" placeholder="wprowadź frazę...." name="keywords"></li>
                        <li>&nbsp;</li>
                        <li><input type="submit" class="btn smallFont" value="SZUKAJ" /></li>
                    </ul>
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ksiazki", "Index", "book")</li>
                    <li>@Html.ActionLink("Koszyk", "cart", "book")</li>
                    @if (Convert.ToString(Session["role"]) == "sprzedawca")
                    {
                        <li>@Html.ActionLink("Uzytkownicy", "index", "user")</li>
                    }

                    <li>@Html.ActionLink("Zamowienia", "showOrder", "book")</li>
                    @if (Session["userId"] != null)
                    {
                        <li>@Html.ActionLink("Wyloguj Się", "LogOut", "user")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Logowanie", "LogIn", "user")</li>
                        <li>@Html.ActionLink("Rejestracja", "create", "user")</li>
                    }


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content"  id="container">
        @RenderBody()


    </div>
    <footer id="footer" class="footer-1">
        <div class="main-footer widgets-dark typo-light">
            <div class="container">
                <div class="row">

                    <div class="col-xs-12 col-sm-6 col-md-3">
                        <div class="widget subscribe no-box">
                            <h5 class="widget-title">EliteBooker<span></span></h5>
                            <p>Internetowa księgarnia, w której zawsze znajdziesz coś ciekawego do przeczytania!</p>
                           
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-3">
                        <div class="widget no-box">
                            <h5 class="widget-title">Nawigacja<span></span></h5>
                            <ul class="thumbnail-widget">
                                <li>
                                    <div class="thumb-content"><a href="/user/create">Rejestracja</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="/user/LogIn">Logowanie</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="/book">Wszystkie Książki</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="/book/cart">Koszyk</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="/book/showOrder">Zamówienia</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="/">Strona główna</a></div>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-3">
                        <div class="widget no-box">
                            <h5 class="widget-title">Zacznij<span></span></h5>
                            <p>Nie masz jeszcze konta? </p>
                            <a class="btn" href="/user/create" target="_blank">ZAREJESTRUJ SIĘ!</a>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-3">

                        <div class="widget no-box">
                            <h5 class="widget-title">Kontakt<span></span></h5>
                            <p>Mój Github</p>
                            <ul class="social-footer2">
                                <li class="">
                                    <a title="github" target="_blank" href="https://github.com/wesoly97">
                                        <img src="~/logoFolder/GitHub-Mark-Light-64px.png" />
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <p>Mikołaj Wesołek © 2021. Wszelkie prawa zastrzeżone</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>

        $.validator.methods.range = function (value, element, param) {
            var globalizedValue = value.replace(",", ".");
            return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
        }

        $.validator.methods.number = function (value, element) {
            return this.optional(element) || /-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
        }
        //Date dd/MM/yyyy
        $.validator.methods.date = function (value, element) {
            var date = value.split("/");
            return this.optional(element) || !/Invalid|NaN/.test(new Date(date[2], date[1], date[0]).toString());
        }
    </script>
</body>
</html>